export const GOT_ALGOLIA_DATA = "GOT_ALGOLIA_DATA";

export const MAKE_ALGOLIA_SEARCH_REQ = "MAKE_ALGOLIA_SEARCH_REQ";

export const RESET_THE_FORM = "RESET_THE_FORM";

export const RESET_SEARCH_FORM_REDUCER = "RESET_SEARCH_FORM_REDUCER";
