export const GOT_HITS_AND_FACETS = "GOT_HITS_AND_FACETS";

export const MAKE_ALGOLIA_SEARCH_REQ = "MAKE_ALGOLIA_SEARCH_REQ";

export const RESET_THE_FORM = "RESET_THE_FORM";

export const RESET_SEARCH_FORM_REDUCER = "RESET_SEARCH_FORM_REDUCER";
